# ---------- Build stage ----------
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

# Copy semua source code
COPY . .

# Build project tanpa menjalankan test
RUN mvn clean package -DskipTests

# ---------- Run stage ----------
FROM eclipse-temurin:17-jre
WORKDIR /app

# Copy hasil build (JAR)
COPY --from=build /app/target/*.jar app.jar

# Expose port (Render pakai PORT env var)
EXPOSE 8080

# Jalankan Spring Boot
CMD ["java", "-jar", "app.jar"]